#!/usr/bin/env python
# coding: utf-8

import json
import sys


def get_input():
    ret = ""
    if len(sys.argv) > 1:
        with open(sys.argv[1]) as f:
            ret = f.read()
    else:
        ret = sys.stdin.read()
    return ret


def main():
    json_string = get_input()
    d = json.loads(json_string)
    output = json.dumps(d, indent=2, ensure_ascii=False, encoding="utf-8")
    sys.stdout.write(output.encode("utf-8"))
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
