#!/usr/bin/env python
# coding: utf-8

import json
import os
import sys


class VendorType(object):
    UNKNOWN = 0
    GODEPS = 1
    VENDOR = 2

    @staticmethod
    def get_type(basename):
        if basename == 'Godeps.json':
            return VendorType.GODEPS
        elif basename == 'vendor.json':
            return VendorType.VENDOR
        return VendorType.UNKNOWN


def update(packages):
    for p in packages:
        cmd = 'go get -u -v %s' % p
        os.system(cmd)


def handle_godeps(file_path):
    data = ''
    with open(file_path) as f:
        data = f.read()
    vendor = json.loads(data)
    packages = [package['ImportPath'] for package in vendor['Deps']]
    update(packages)


def handle_vendor(file_path):
    data = ''
    with open(file_path) as f:
        data = f.read()
    vendor = json.loads(data)
    packages = [package['path'] for package in vendor['package']]
    update(packages)


if __name__ == '__main__':
    file_path = sys.argv[1]
    vendor_type = VendorType.get_type(os.path.basename(file_path))
    if vendor_type == VendorType.GODEPS:
        handle_godeps(file_path)
    elif vendor_type == VendorType.VENDOR:
        handle_vendor(file_path)
    else:
        print 'unknown type for %s' % file_path
